#!/usr/bin/env sh

set -e

if [ "${PLUGIN_DEBUG}" == "true" ]; then
    # debug: "true"
    set -x
fi

if [[ -z "${PLUGIN_APPLY_FILE}" && -z "${PLUGIN_APPLY_KUSTOMIZE}" ]]; then
    echo "Variable PLUGIN_APPLY_FILE or PLUGIN_APPLY_KUSTOMIZE is required" > /dev/stderr
    exit 1
elif [[ ! -z "${PLUGIN_APPLY_FILE}" && ! -z "${PLUGIN_APPLY_KUSTOMIZE}" ]]; then
    echo "Exactly one of PLUGIN_APPLY_FILE or PLUGIN_APPLY_KUSTOMIZE is allowed" > /dev/stderr
    exit 1
fi

kubeauth

if [ ! -z "${PLUGIN_APPLY_FILE}" ]; then
    kubectl apply -f "${PLUGIN_APPLY_FILE}"
elif [ ! -z "${PLUGIN_APPLY_KUSTOMIZE}" ]; then
    kubectl apply -k "${PLUGIN_APPLY_KUSTOMIZE}"
else
    exit 1
fi
